#!/bin/sh
set -eo pipefail
if [ ! $REDIS_DEFAULT_PORT ]; then
    REDIS_DEFAULT_PORT="6379"
fi

if [ ! $REDIS_DEFAULT_DATABASE ]; then
    REDIS_DEFAULT_DATABASE="3"
fi

if [ ! $REDIS_LIST_PORT ]; then
    REDIS_LIST_PORT="6379"
fi

if [ ! $REDIS_LIST_DATABASE ]; then
    REDIS_LIST_DATABASE="15"
fi

if [ ! $MYSQL_DEFAULT_PORT ]; then
    MYSQL_DEFAULT_PORT="3306"
fi

if [ ! $MYSQL_DEFAULT_DATABASE ]; then
    MYSQL_DEFAULT_DATABASE="shentu"
fi

if [ ! $MYSQL_SHENTU_PORT ]; then
    MYSQL_SHENTU_PORT="3306"
fi

if [ ! $MYSQL_SHENTU_DATABASE ]; then
    MYSQL_SHENTU_DATABASE="shentu"
fi
sed -i "s/{ENV}/pro/g; s/{DEBUG}/false/g;s/{HTTP_PORT}/9001/g; s/{REDIS_DEFAULT_HOST}/${REDIS_DEFAULT_HOST}/g; s/{REDIS_DEFAULT_PORT}/${REDIS_DEFAULT_PORT}/g; s/{REDIS_DEFAULT_PASSWORD}/${REDIS_DEFAULT_PASSWORD}/g; s/{REDIS_DEFAULT_DATABASE}/${REDIS_DEFAULT_DATABASE}/g; s/{REDIS_LIST_HOST}/${REDIS_LIST_HOST}/g; s/{REDIS_LIST_PORT}/${REDIS_LIST_PORT}/g; s/{REDIS_LIST_PASSWORD}/${REDIS_LIST_PASSWORD}/g; s/{REDIS_LIST_DATABASE}/${REDIS_LIST_DATABASE}/g; s/{MYSQL_DEFAULT_HOST}/${MYSQL_DEFAULT_HOST}/g; s/{MYSQL_DEFAULT_PORT}/${MYSQL_DEFAULT_PORT}/g; s/{MYSQL_DEFAULT_USER}/${MYSQL_DEFAULT_USER}/g; s/{MYSQL_DEFAULT_PASSWORD}/${MYSQL_DEFAULT_PASSWORD}/g; s/{MYSQL_DEFAULT_DATABASE}/${MYSQL_DEFAULT_DATABASE}/g; s/{MYSQL_SHENTU_HOST}/${MYSQL_SHENTU_HOST}/g; s/{MYSQL_SHENTU_PORT}/${MYSQL_SHENTU_PORT}/g; s/{MYSQL_SHENTU_USER}/${MYSQL_SHENTU_USER}/g; s/{MYSQL_SHENTU_PASSWORD}/${MYSQL_SHENTU_PASSWORD}/g; s/{MYSQL_SHENTU_DATABASE}/${MYSQL_SHENTU_DATABASE}/g" /app/config.yaml
exec "$@"